info:
  app:
    name: Marvel API V2
    description: New version of Marvel API to provide Marvel Comics data
    version: 2.0

spring:
  profiles:
    active: local
  security:
    user:
      name: test
      password: marvel
  data:
    mongodb:
      uri: mongodb://root:marvel@localhost:27017/
      # if the port is the default 27017 is not necessary to add the uri property,
      # but the properties username and password conflicts to embedded mongodb
      #      username: root
      #      password: marvel
      database: local