info:
  app:
    name: Marvel API V2
    description: New version of Marvel API to provide Marvel Comics data
    version: 2.0

spring:
  profiles:
    active: local
  security:
    user:
      name: test
      password: marvel